### ISSUE TITLE
when cpp2sky could support virtual database?

### ISSUE THREAD

**Issue by peacine** [SkyAPM/cpp2sky#122]

**Comment by wu-sheng** [comment]
Virtual Database is just about tag, as cpp2sky is a SDK.
You could set necessary information you need.

**Comment by peacine** [comment]
Thanks for your reply. What you mean is that I can implement virtual database function by tag，but It can be displayed on SkyWalking UI?

**Comment by peacine** [comment]
> Virtual Database is just about tag, as cpp2sky is a SDK. You could set necessary information you need.
Thanks for your reply. What you mean it that I can implement virtual database function by tag, but it can be displayed on SkyWalking UI 'Virutal Database'?

**Comment by wu-sheng** [comment]
Follow the doc, UI linking to you

https://skywalking.apache.org/docs/main/next/en/setup/service-agent/virtual-database/

We had provided all you need.

**Comment by peacine** [comment]
> Follow the doc, UI linking to you
> 
> https://skywalking.apache.org/docs/main/next/en/setup/service-agent/virtual-database/
> 
> We had provided all you need.

Thank you. I will try it.
