### ISSUE TITLE
how to report mertics data and logging data with cpp2sky sdk?

### ISSUE THREAD

**Issue by jackxuqq** [SkyAPM/cpp2sky#125]
how to report mertics data and logging data with cpp2sky sdk?

**Comment by wu-sheng** [comment]
AFAIK, these are not implemented.

**Comment by jackxuqq** [comment]
Is there a plan to implement metrics  data and logging data report？

**Comment by wu-sheng** [comment]
There is no one adding new features to this project.

Currently, cpp2sky is for building SkyWalking tracer in envoy. If someone wants to add more, we are open to discuss
