### ISSUE TITLE
Tracing.proto and Common.proto pollute global namepace

### ISSUE THREAD

**Issue by liberize** [SkyAPM/cpp2sky#36]
Tracing.proto and Common.proto introduce lots of symbol into global namepace, like `Command`, `SpanType`.. which conflict with my other header files.
Consider adding `package <NAMESPACE>;` to proto files, however, this will change method name from `/TraceSegmentReportService/collect` to `/<NAMESPACE>.TraceSegmentReportService/collect` which is not recognized by skywalking server. Maybe fix it manually?

**Comment by Shikugawa** [comment]
@wu-sheng @lizan I think that this feature should be introduced before 0.1.0 because it will cause same problem when integrating Envoy.

**Comment by lizan** [comment]
This is more a issue of data-collect-protocol issue. @wu-sheng ?

**Comment by wu-sheng** [comment]
We are diacussing there, how it works in today's envoy?

**Comment by Shikugawa** [comment]
@liberize As for discussion with SkyWalking maintainers, we can't introduce package name because it will cause serious breaking change without C++ dedicated namespacing option like java. This problem is not caused on Envoy which is large C++ application in the world integrating with SkyWalking data collect protocol. 
https://github.com/envoyproxy/envoy/blob/master/source/extensions/tracers/skywalking/skywalking_types.h#L11
So personally I recommend you to use namespace in your C++ application.

**Comment by wu-sheng** [comment]
We also want to check, cpp tracer is not using your grpc client. Is there still a conflict?

**Comment by Shikugawa** [comment]
It will be used in general, but envoy won't.

**Comment by wu-sheng** [comment]
Even in general, tracing backend is different from the user codes. So, I am expecting no conflict.

**Comment by Shikugawa** [comment]
This problem will caused when compile. It will conflict, such as between `Command` class on user's application it includes cpp2sky and `Command` class on data collect protocol definition. So It might have no relation.

**Comment by lizan** [comment]
@wu-sheng it is the protobuf generated class, so regardless of the gRPC client, it pollutes the global namespace.

**Comment by wu-sheng** [comment]
> so it might be inevitable if you don't use cpp2sky grpc stub.

I was expecting no one is using like this. Unless like envoy, it could take care of this smoothly already.
Another block is adding this breaks all changes in the main upstream, we can't make it easily. We have to wait next time the whole protocol upgrade, which are years away most likely.

> it is the protobuf generated class, so regardless of the gRPC client, it pollutes the global namespace.

@lizan I don't know cpp, it there a chance to separate the compiling? In all language before, it has internal package system, not using this package option, like java package option. But once this is added, grpc service name changed. 
I hope we could introduce how envoy resolve this, and don't have to change it. Such as  @Shikugawa idea, use our reporter only.

**Comment by lizan** [comment]
No the unfortunate part is protobuf doesn't allow overriding C++ namespace, which worth a separate issue in protobuf. Aside from that, I added recommendation to https://github.com/apache/skywalking/issues/6019#issuecomment-747194576.

Re: how it solved in Envoy, no it isn't, at Envoy we clearly namespaced everything else (including those C libraries which have clear prefix in the symbol names they exported), but it shouldn't be the excuse that SkyWalking proto can pollute the namespace.
