### ISSUE TITLE
Add bazel support for SkyWalking data collect protocol

### ISSUE THREAD

**Issue by Shikugawa** [SkyAPM/cpp2sky#6]
Related with https://github.com/SkyAPM/cpp2sky/pull/5

Commented on [here](https://github.com/SkyAPM/cpp2sky/blob/main/bazel/repositories.bzl#L10).
We use private fork to enable building data collect protocol with Bazel right now, so we should upstream this in the future. (before 0.1.0 release)

**Comment by wu-sheng** [comment]
> (before 0.0.1 release)

Suggest use 0.1.0, as in skywalking ecosystem, the last min version means bug fix only :)
