### ISSUE TITLE
Log & Trace integration

### ISSUE THREAD

**Issue by wu-sheng** [SkyAPM/cpp2sky#75]
SkyWalking is enhancing its log integration capability, so, it will accept logs collected by popular tools, such as fluentd, filebeat.
It is better cpp2sky could inject the trace context information as a part of log text, which could make SkyWalking backend links logs and traces together.
You could take Java agent's implementation for a reference, http://skywalking.apache.org/docs/main/v8.5.0/en/setup/service-agent/java-agent/application-toolkit-log4j-1.x/#print-skywalking-context-in-your-logs

**Comment by Shikugawa** [comment]
@wu-sheng It means that we should put out (or sending integrated trace logs to log collector) the trace ID and issued time and so on at agent side. Correct?

**Comment by wu-sheng** [comment]
We don't have to deal with the log collecting and sending. But we should inject trace context text into the log output and ALS.

**Comment by wu-sheng** [comment]
Like this plugin of go does. https://github.com/SkyAPM/go2sky-plugins/pull/19
