### ISSUE TITLE
I have a project write by C++11,want to import cpp2sky which is write by C++17, can we suport C++11?

### ISSUE THREAD

**Issue by xlj** [SkyAPM/cpp2sky#88]
I have a project write by C++11,the project is too huge to fit C++17，can cpp2sky suport C++11?

**Comment by wbpcode** [comment]
Sorry, I am not sure if this reply is too late. It's hard for cpp2sky to support C++17 for know.

**Comment by wu-sheng** [comment]
It is supported now.
